version: '3'

services:
  postgres:
    image: postgres:15
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: appDB
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_net

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.0
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: appDB
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - keycloak_net

  backend:
    build: ./backend
    container_name: whiteboard_backend
    volumes:
      - ./backend:/app
    command: npm run dev  
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=appDB
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - PORT=4000
      - KEYCLOAK_URL=http://keycloak:8080
    depends_on:
      - postgres
      - keycloak
    networks:
      - keycloak_net

volumes:
  postgres_data:

networks:
  keycloak_net:
